apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: threatsimgpt

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - workers.yaml
  - hpa.yaml

configMapGenerator:
  - name: threatsimgpt-config
    files:
      - config.yaml=../../../config.yaml

generatorOptions:
  disableNameSuffixHash: true
