{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threatsimgpt.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "threatsimgpt.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Files.Get .Values.config.configFile | indent 4 }}
{{- end }}
